### ISSUE TITLE
When will the model and the source be open to the public?

### ISSUE THREAD

**Issue by maxmarketit** [sidgairo18/unsupervised-style-learning#1]
Hello, great paper,

  I am wondering when I can see the source...

  to decide if I need to implement myself...

  Thank you for your great commitment and dedication.

**Comment by biswassanket** [comment]
I liked the paper too. It would be great if you could make the code and pre-trained models available.

**Comment by sidgairo18** [comment]
Hi all, the src code and dataset information have been released. Would be happy for your feedback or any assistance.
